a=int(input("enter the no."))
b=int(input("enter the no."))
c=int(input("enter the no."))
d=int(input("enter the no."))
e=int(input("enter the no."))
avg=(a+b+c+d+e)
print("enter the 5 number is:",avg)